### ISSUE TITLE
Fix wonky-looking bibliography URLs

### ISSUE THREAD

**Issue by niklad** [niklad/Specialization-Project-LaTeX#3]
Seems to be overfull, and awkward formatting.

**Comment by niklad** [comment]
Look into using \xurl (or something) instead of \url, ask Brage again if no work.

**Comment by niklad** [comment]
Might be enough to remove the doi stuff, if that is ok

**Comment by camillgh** [comment]
Use

```\setcounter{biburlnumpenalty}{100}```

to set a custom line break for urls in bibliography. This should work for DOI stuff as well.

**Comment by camillgh** [comment]
Use

```\setcounter{biburlnumpenalty}{100}```

to set a custom line break for urls in bibliography. This should work for DOI stuff as well.

From the [`biblatex` docs](https://www.google.com/url?sa=t&source=web&cd=&ved=2ahUKEwj-_vyUzp78AhXSwosKHVR7C0sQFnoECBcQAQ&url=https%3A%2F%2Fctan.math.illinois.edu%2Fmacros%2Flatex%2Fcontrib%2Fbiblatex%2Fdoc%2Fbiblatex.pdf&usg=AOvVaw2zP1E2Yqvxr9qJZfZlzGzo):

![Screenshot_2022-12-29-11-25-41-26_e2d5b3f32b79de1d45acd1fad96fbb0f~2.jpg](https://user-images.githubusercontent.com/36198373/209938413-af9e7237-6c40-47a4-bc50-ebe56b3449fc.jpg)
